version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    networks:
      - app-network
    depends_on:
      - database
      - cache
    environment:
      - MONGODB_URI=mongodb://database:27017/tasks
      - REDIS_URI=redis://cache:6379

  database:
    image: mongo:7.0
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tasks

  cache:
    image: redis:7.2-alpine
    networks:
      - app-network
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: 